aristotle/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
import aristotle.views as core_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', core_views.home, name='home'),
    path('authentication/', include('authentication.urls'), name='authentication'),
    path('forum/', include('forum.urls'), name='forum'),
]

forum/urls.py
from forum.views_folder import views_assignments, views_courses, views_modules, views_students, views_submissions
from django.urls import path

from .views_folder import views

app_name = 'forum'
urlpatterns = [
    path('', views.index, name='index'),
    path('course_id=<course_id>/', views.index, name='index'),
    
    path('course_id=<course_id>/students/', views_students.students, name='students'),
    path('course_id=<course_id>/students/grades/student_id=<student_id>/', views_students.studentgrades, name='studentgrades'),

    path('course_id=<course_id>/courses/', views_courses.courses, name='courses'),
    path('courses/', views_courses.courses, name='courses'),
    path('course_id=<course_id>/setcourse/', views_courses.setcourse, name='setcourse'),
    path('course_id=<course_id>/removefrompinned/', views_courses.removefrompinned, name='removefrompinned'),
    path('createcourse/', views_courses.createcourse, name='createcourse'),

    path('course_id=<course_id>/assignments/', views_assignments.assignments, name='assignments'),
    path('course_id=<course_id>/assignments/newassignment/', views_assignments.newassignment, name='newassignment'),
    path('course_id=<course_id>/assignments/assignment_id=<assignment_id>/delete/', views_assignments.delete_assignment, name='delete_assignment'),
    path('course_id=<course_id>/assignments/assignment_id=<assignment_id>/', views_assignments.assignmentdetails, name='assignmentdetails'),
    
    path('course_id=<course_id>/assignments/assignment_id=<assignment_id>/submit/', views_submissions.newsubmission, name='newsubmission'),
    path('course_id=<course_id>/assignments/submissions/assignment_id=<assignment_id>/student_id=<student_id>/', views_submissions.viewsubmission, name='viewsubmission'),
    
    path('course_id=<course_id>/modules/', views_modules.modules, name='modules'),
    path('course_id=<course_id>/createmodule/', views_modules.createmodule, name='createmodule'),
    path('course_id=<course_id>/deletemodule/module_id=<module_id>', views_modules.deletemodule, name='deletemodule'),
]

forum/models.py
from django.conf import settings
from django.db import models
import uuid

from django_quill.fields import QuillField

# Create your models here.
class Course(models.Model):
    name = models.CharField(max_length=100)
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='course_of_owner'
    )
    students = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='course_of_student',
        blank=True
    )
    uuid = models.UUIDField(
        default=uuid.uuid4,
        editable=False
    )

    def __str__(self):
        return self.name

class AssignmentModule(models.Model):
    name = models.CharField(max_length=100)
    course = models.ForeignKey(
        Course,
        on_delete=models.CASCADE
    )
    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['name', 'course'],
                name='unique name'
            )
        ]
    
    def __str__(self):
        return self.name

class Assignment(models.Model):
    course = models.ForeignKey(
        Course,
        on_delete=models.CASCADE,
        related_name='assignments_of_course'
    )
    module = models.ForeignKey(
        AssignmentModule,
        on_delete=models.SET_NULL,
        related_name='assignments_of_module',
        null=True
    )
    title = models.CharField(max_length=100)
    start_datetime = models.DateTimeField(null=True, blank=True)
    end_datetime = models.DateTimeField(null=True, blank=True)
    description = QuillField()
    total_points = models.FloatField(null=True, blank=True)
    class Meta:
        ordering = ['end_datetime', 'title']
    
    def __str__(self):
        return self.title

class Grade(models.Model):
    student = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="grade_of_student"
    )
    assignment = models.ForeignKey(
        Assignment,
        on_delete=models.CASCADE,
        related_name="grade_of_assignment"
    )
    earned_points = models.FloatField(null=True, blank=True)
    feedback = models.CharField(max_length=1000, null=True, blank=True)

    def __str__(self):
        return self.assignment.title + " [grade]"

class Submission(models.Model):
    student = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="submission_of_student"
    )
    assignment = models.ForeignKey(
        Assignment,
        on_delete=models.CASCADE,
        related_name="submission_of_assignment"
    )
    details = QuillField()
    submit_datetime = models.DateTimeField(auto_now_add=True, blank=True)

    def __str__(self):
        return self.assignment.title + " [submission] id: " + str(self.id)

class UserData(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='userdata_of_user',
    )
    pinnedcourses = models.ManyToManyField(
        Course,
        related_name='userdata_of_pinnedcourse',
        blank=True
    )

forum/forms.py
from django import forms
from django_quill.fields import QuillFormField

class CreateCourseForm(forms.Form):
    name = forms.CharField(max_length=100)

class CreateModuleForm(forms.Form):
    name = forms.CharField(max_length=100)

class JoinCourseForm(forms.Form):
    uuid = forms.UUIDField()

class NewSubmission(forms.Form):
    details = QuillFormField()

class CreateAssignmentForm(forms.Form):
    title = forms.CharField(max_length=100)
    start_datetime = forms.DateTimeField(required=False)
    end_datetime = forms.DateTimeField(required=False)
    description = QuillFormField(required=False)
    total_points = forms.FloatField(required=False)
    module = forms.CharField(required=False, widget=forms.Select)

forum/views_folder/views.py
from forum.views_folder.utilities import alwaysContext
from django.shortcuts import render, redirect
from ..models import Assignment, Course, UserData
from django.db.models import Q
import datetime

# Create your views here.
def index(request, course_id=None):
    if not request.user.is_authenticated:
        return redirect('home')
    context = alwaysContext(request, course_id)
    context["assignments"] = Assignment.objects.filter(
        Q(course__owner=request.user)
        | Q(course__students=request.user)
    ).filter(
        end_datetime__range=[str(datetime.datetime.now()), str(datetime.datetime.now() + datetime.timedelta(days=7))]
    ).exclude(
        end_datetime__isnull=True
    )
    context["courses"] = Course.objects.filter(
        Q(owner=request.user)
        | Q(students=request.user)
    )
    if request.method == "POST" and "pinselect" in request.POST:
        pincourseid = int(request.POST["pinselect"])
        print(request.user.id)
        userdata = UserData.objects.get(user=request.user)
        userdata.pinnedcourses.add(Course.objects.get(id=pincourseid))
    context["pinnedcourses"] = Course.objects.filter(
        Q(userdata_of_pinnedcourse__user = request.user)
    )
    return render(request, "index.html", context)

forum/templates/assignmentdetails_student.html
{% extends 'base.html' %}

{% block title %}
Assignment Details: {{assignment.title}}
{% endblock %}

{% block content %}
<h2>Assignment: {{assignment.title}}</h2>
<p><i>
    <b>Start date: </b>{% if assignment.start_datetime %}{{assignment.start_datetime}}{% else %}--{% endif %}<br>
    <b>End date: </b>{% if assignment.end_datetime %}{{assignment.end_datetime}}{% else %}--{% endif %}<br>
    <b>Grade: </b>{% if grade.earned_points %}{{grade.earned_points}}{% else %}--{% endif %}
    / {% if assignment.total_points %}{{assignment.total_points}}{% else %}--{% endif %}
    {% if grade.feedback %}
    <br><b>Feedback: </b>{{grade.feedback|linebreaksbr}}
    {% endif %}
</i></p>
<h3>Description:</h3>
<div class="card mb-3">
    <div class="card-body bg-light">
        {% autoescape off %}
        {{assignment.description.html |safe}}
        {% endautoescape %}
        <style>.card-body p {margin: 0}</style>
    </div>
</div>
<div style="display: flex; flex-direction: row; align-items: center; justify-content: space-between;">
    <h3>Submissions:</h3>
    <a href="{% url 'forum:newsubmission' course_id=selected_course.uuid assignment_id=assignment.id %}"><div class="btn btn-primary mb-2">+ New submission</div></a>
</div>
{% if submissions|length == 0 %}
No submissions yet!
{% endif %}
{% for submission in submissions %}
<div class="card mb-3">
    <div class="card-header"><i>{{submission.submit_datetime}}</i></div>
    <div class="card-body">
        {% autoescape off %}
        {{submission.details.html |safe}}
        {% endautoescape %}
        <style>.card-body p {margin: 0}</style>
    </div>
</div>
{% endfor %}
{% endblock %}

forum/templates/assignmentdetails_teacher.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Assignment Details: {{assignment.title}}
{% endblock %}

{% block content %}
<form action="{% url 'forum:assignmentdetails' course_id=selected_course.uuid assignment_id=assignment.id %}" method="POST">
    {% csrf_token %}
    <div style="display: flex; flex-direction: row; justify-content: space-between;">
        <div>
            <div class="form-group">
                <label for="title">Title:</label>
                {{form.title}}
                <script>
                    $("input[name='title']").addClass("form-control")
                </script>
            </div>
            <div class="form-group">
                <label for="start_datetime">Start:</label>
                {{form.start_datetime}}
                <script>
                    $("input[name='start_datetime']").addClass("form-control")
                    $("input[name='start_datetime']").val("{{assignment.start_datetime|date:'Y-m-d\TH:i'}}")
                </script>
            </div>
            <div class="form-group">
                <label for="end_datetime">Deadline:</label>
                {{form.end_datetime}}
                <script>
                    $("input[name='end_datetime']").addClass("form-control")
                    $("input[name='end_datetime']").val("{{assignment.end_datetime|date:'Y-m-d\TH:i'}}")
                </script>
            </div>
            <div class="form-group">
                <label for="description">Description:</label>
                {% autoescape off %}
                {{form.description}}
                <script>
                    $(".ql-editor").html("{{assignment.description.html}}")
                </script>
                {% endautoescape %}
            </div>
            <div class="form-group">
                <label for="total_points">Total points:</label>
                {{form.total_points}}
                <script>
                    $("input[name='total_points']").addClass("form-control")
                </script>
            </div>
            <div class="form-group">
                <label for="module">Module:</label>
                {{form.module}}
                <script>
                    $("select[name='module']").addClass("form-select")
                    {% for assnmodule in modules %}
                    document.getElementsByName("module")[0].innerHTML += `<option value="{{assnmodule}}">{{assnmodule}}</option>`;
                    {% endfor %}
                </script>
            </div>
        </div>
        <div class="btn btn-danger" onclick="delete_assn()" style="height: fit-content">Delete assignment</div>
        <script>
            function delete_assn() {
                if (confirm("Are you sure you want to delete this assignment?")) {
                    location.href = "{% url 'forum:delete_assignment' course_id=selected_course.uuid assignment_id=assignment.id %}";
                }
            }
        </script>
    </div>
    <br>
    <input class="btn btn-primary mb-2" type="submit" value="Save changes">
    {% if savedmessage %}
    <div class="alert alert-success">{{savedmessage}}</div>
    {% endif %}
</form>
<h2>Review submissions:</h2>
<table class="table">
    <thead>
        <tr>
            <th>Student</th>
            <th># Submissions</th>
            <th>Grade</th>
            <th>Percent grade</th>
            <th>Review submissions</th>
        </tr>
    </thead>
    <tbody>
        {% for student in students %}
        <tr>
            <td>{{student.username}}</td>
            <td>{{student.nosubmissions}}</td>
            <td>
                {% if student.grade != None %}{{student.grade}}{% else %}--{% endif %}
                / {% if assignment.total_points != None %}{{assignment.total_points}}{% else %}--{% endif %}
            </td>
            <td>{{student.percentgrade}}%</td>
            <td><a href="{{student.link}}"><div class="btn btn-primary">Review submission</div></a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<link rel="stylesheet" href="{% static 'css/table.css' %}">

<script>
    document.getElementsByName("start_datetime")[0].type = "datetime-local";
    document.getElementsByName("end_datetime")[0].type = "datetime-local";
    document.getElementsByName("module")[0].innerHTML += `<option value="No module"></option>`;
    document.getElementsByName("module")[0].value = "{{curr_module}}";
</script>

{% endblock %}

forum/templates/assignments_student.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{{page_title}}
{% endblock %}

{% block content %}
<h2>{{page_title}}</h2>
<div style="display: flex; flex-direction: row; align-items: center; justify-content: space-between;">
    {% if assignments|length > 0 %}<p>The assignments in <b>{{selected_course.name}}</b>.</p>{% else %}<p>No assignments yet!</p>{% endif %}
</div>

<form method="POST">
    {% csrf_token %}
    <div class="card bg-light">
        <div class="card-body">
            <label>Filter by module: <select name="modulefilter" class="form-select">
                <option disabled selected>Select module</option>
                {% for module in modules %}<option value="{{module.id}}">{{module.name}}</option>{% endfor %}
            </select></label>
            <input class="btn btn-primary" type="submit" value="Submit">
            <a href=""><div class="btn btn-danger" style="background-color: var(--button-red);">Clear</div></a>
        </div>
    </div>
</form>

<table class="table table-hover">
    <thead>
        <tr>
            <th>Assignment</th>
            <th>Start Date</th>
            <th>Due Date</th>
            <th>Grade</th>
            <th>Submitted</th>
        </tr>
    </thead>
    <tbody>
    {% for assignment in assignments %}
        <tr onclick="location.href='{% url 'forum:assignmentdetails' course_id=selected_course.uuid assignment_id=assignment.id %}'" style="cursor: pointer">
            <td>{{assignment.title}}</td>
            <td>{% if assignment.start_datetime %}{{assignment.start_datetime}}{% else %}--{% endif %}</td>
            <td>{% if assignment.end_datetime %}{{assignment.end_datetime}}{% else %}--{% endif %}</td>
            <td>{% if assignment.earned_points %}{{assignment.earned_points}}{% else %}--{% endif %}
                / {% if assignment.total_points %}{{assignment.total_points}}{% else %}--{% endif %}</td>
            <td>
                {% if assignment.submitted %}
                Yes
                {% else %}
                <span class="badge bg-danger">No</span>
                {% endif %}
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>
<div class="card">
    <div class="card-body bg-light">
        <b>Cumulative grade:</b> {{cum_num}}/{{cum_den}} &#8776; {% widthratio cum_num cum_den 100 %}%
    </div>
</div>
{% endblock %}

forum/templates/assignments_teacher.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Assignments
{% endblock %}

{% block content %}
<h2>Assignments</h2>
<div style="display: flex; flex-direction: row; align-items: center; justify-content: space-between;">
    {% if assignments|length > 0 %}<p>The assignments in <b>{{selected_course.name}}</b>.</p>{% else %}<p>No assignments yet!</p>{% endif %}
    <a href="{% url 'forum:newassignment' course_id=selected_course.uuid %}"><div class="btn btn-primary mb-3">+ New assignment</div></a>
</div>
<form method="POST" action="{% url 'forum:assignments' course_id=selected_course.uuid %}">
    {% csrf_token %}
    <div class="card bg-light">
        <div class="card-body">
            <label>Filter by module: <select name="modulefilter" class="form-select">
                <option disabled selected>Select module</option>
                {% for module in modules %}<option value="{{module.id}}">{{module.name}}</option>{% endfor %}
            </select></label>
            <input class="btn btn-primary" type="submit" value="Submit">
            <a href="{% url 'forum:assignments' course_id=selected_course.uuid %}"><div class="btn btn-danger" style="background-color: var(--button-red);">Clear</div></a>
        </div>
    </div>
</form>
<table class="table table-hover">
    <thead>
        <tr>
            <th>Assignment</th>
            <th>Start Date</th>
            <th>Due Date</th>
            <th>Submitted</th>
            <th>Graded</th>
        </tr>
    </thead>
    <tbody>
        {% for assignment in assignments %}
        <tr onclick="location.href='{% url 'forum:assignmentdetails' course_id=selected_course.uuid assignment_id=assignment.id %}'" style="cursor:pointer">
            <td>{{assignment.title}}</td>
            <td>{% if assignment.start_datetime != None %}{{assignment.start_datetime}}{% else %}--{% endif %}</td>
            <td>{% if assignment.end_datetime != None %}{{assignment.end_datetime}}{% else %}--{% endif %}</td>
            <td>{% if assignment.submitted != None %}{{assignment.submitted}}{% else %}--{% endif %}/{% if assignment.nostudents != None %}{{assignment.nostudents}}{% else %}--{% endif %}</td>
            <td>
                <span {% if assignment.graded != assignment.submitted %}class="badge bg-danger"{% endif %}>
                {% if assignment.graded != None %}{{assignment.graded}}{% else %}--{% endif %}/{% if assignment.submitted != None %}{{assignment.submitted}}{% else %}--{% endif %}
                </span>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

forum/templates/courses.html
{% extends 'base.html' %}

{% block title %}
Courses
{% endblock %}

{% block content %}
<h2>Your Courses</h2>
{% if courses|length > 0 %}<p>View your courses below! Click on the course title to select that course.</p>{% else %}<p>No courses yet!</p>{% endif %}
{% if selected_course %}
<p>Your current course selection is <b>{{selected_course.name}}</b>.</p>
{% endif %}

<div class="list-group mb-3">
    {% for course in courses %}
    <a href="{% url 'forum:setcourse' course_id=course.uuid %}" class="list-group-item list-group-item-action{% ifequal selected_course.uuid course.uuid %} list-group-item-primary{% endifequal %}">
        <span>{{course.name}}</span>
        {% if course.owner == request.user %}<span class="badge rounded-pill bg-primary ms-4">Owner</span>{% endif %}
    </a>
    {% endfor %}
</div>
<a href="{% url 'forum:createcourse' %}" class="btn btn-primary mb-5">
    + New course
</a>

<div class="card">
    <div class="card-header">Join a Course</div>
    <div class="card-body" style="background-color: white;">
        <p>Join a course by entering its UUID:</p>
        <form action="#" method="POST">
            {% csrf_token %}
            {{form.uuid}}
            <input type="submit" value="Submit" class="btn btn-primary mt-3">
            {% if error %}<br><span style="color:red">{{error}}</span>{% endif %}
        </form>
    </div>
</div>
<script>$("input[name='uuid']").addClass("form-control")</script>
{% endblock %}

forum/templates/createcourse.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
Create Course
{% endblock %}

{% block content %}
<h2>Create a new course</h2>
<form action="{% url 'forum:createcourse' %}" method="post" class="form">
    {% csrf_token %}
    {{form|crispy}}
    <input type="submit" value="Submit" class="btn btn-primary mt-3">
</form>
{% endblock %}

forum/templates/createmodule.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
Create Module
{% endblock %}

{% block content %}
<h2>Create a new module</h2>
<form action="{% url 'forum:createmodule' course_id=selected_course.uuid %}" method="post" class="form">
    {% csrf_token %}
    {{form|crispy}}
    <input type="submit" value="Submit" class="btn btn-primary mt-3">
</form>
{% endblock %}

forum/templates/index.html
{% extends 'base.html' %}

{% block title %}
Home
{% endblock %}

{% block content %}
<div style="display: flex; flex-direction: row; flex-wrap: wrap">
    <div style="display: flex; flex-direction: column; flex: 2 2 auto">
        <div>
            <h2>HQ</h2>
            <p>
                Welcome to your <b>aristotle</b> HQ! Use the navigation bar to the left to manage your courses and students.
            </p>
        </div>
        <div style="max-width: 800px">
            <a href="https://github.com/dabslee/aristotle/blob/master/README.md" class="card placard">
                <div class="card-body" style="display: flex; flex-direction: row; justify-content: space-between;">
                    <div>
                        <h5 class="card-title">Project README</h5>
                        <p>Check out the project's README.md on GitHub to learn about aristotle° as a programming project.</p>
                    </div>
                    <h2 class="bi bi-journal-text text-muted"></h2>
                </div>
            </a>
            <!-- <a href="" class="card placard">
                <div class="card-body" style="display: flex; flex-direction: row; justify-content: space-between;">
                    <div>
                        <h5 class="card-title">User Guide</h5>
                        <p>Whether you're new to aristotle° or just want to learn how to use it better, check out this user guide to become an aristotle° expert.</p>
                    </div>
                    <h2 class="bi bi-clipboard-check text-muted"></h2>
                </div>
            </a> -->
            <a href="https://github.com/dabslee/aristotle/releases" class="card placard">
                <div class="card-body" style="display: flex; flex-direction: row; justify-content: space-between;">
                    <div>
                        <h5 class="card-title">Dev Notes</h5>
                        <p>Check out the development notes to view previous versions of this project and keep track of feature additions.</p>
                    </div>
                    <h2 class="bi bi-window-sidebar text-muted"></h2>
                </div>
            </a>
        </div>
    </div>
    <div style="flex: 0 2 700px">
        <div class="card">
            <div class="card-header">Upcoming assignments (next 7 days)</div>
            <div class="card-body" style="padding: 15px 30px">
                {% for assn in assignments %}
                <a href="{% url 'forum:assignmentdetails' course_id=assn.course.uuid assignment_id=assn.id %}" class="item">
                    <span>{{assn.title}}</span>
                    <span>{{assn.end_datetime}}</span>
                </a>
                {% endfor %}
                {% if assignments|length == 0 %}
                <span>No assignments due in the next 7 days!</span>
                {% endif %}
            </div>
        </div>
        <div class="card mt-3">
            <div class="card-header">Pinned Courses</div>
            <div class="card-body" style="padding: 15px 30px">
                {% for course in pinnedcourses %}
                <div class="item">
                    <a href="{% url 'forum:setcourse' course_id=course.uuid %}">{{course.name}}</span>
                    <a href="{% url 'forum:removefrompinned' course_id=course.uuid %}"><i class="bi bi-x link-secondary"></i></a>
                </div>
                {% endfor %}
                {% if pinnedcourses|length == 0 %}
                <p>No pinned courses yet!</p>
                {% endif %}
                <form
                {% if course.id %}action="{% url 'forum:index' course_id=selected_course.uuid %}"{% else %}action="{% url 'forum:index' %}"{% endif %}
                method="post"
                style="display: flex; flex-direction: row; align-items: center; justify-content: center;"
                class="mt-2">
                    {% csrf_token %}
                    <select name="pinselect" class="form-select form-select-sm me-2" style="flex: 2 2 auto">
                        <option value="" disabled selected>Select a course</option>
                        {% for course in courses %}
                        <option value="{{course.id}}">{{course.name}}</option>
                        {% endfor %}
                    </select>
                    <input type="submit" class="btn btn-secondary btn-sm" value="Pin"></input>
                </form>
            </div>
        </div>
    </div>
</div>
<style>
    .placard {
        margin-right: 50px;
        margin-bottom: 15px;
        color: black;
    }
    .placard:hover {
        box-shadow: 5px 5px 20px rgba(0,0,0,0.1);
    }
    .item {
        display: flex;
        flex-direction: row;
        justify-content: space-between;
    }
</style>
{% endblock %}

forum/templates/modules.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Modules
{% endblock %}

{% block content %}
<h2>Modules</h2>
<form method="POST" action="{% url 'forum:modules' course_id=selected_course.uuid %}">
    {% csrf_token %}
    {% if selected_course.owner == request.user %}
    <div class="mb-3" style="display: flex; flex-direction: row; justify-content: space-between; align-items: center;">
        
        <div class="card bg-light">
            <div class="card-body" style="max-width: 500px; flex-direction: row; align-items: center">
                <label class="me-3" style="flex-grow: 1; min-width: fit-content">Assign selected to module:</label>
                <select name="moduleassign" class="form-select" style="display: inline-block; width: fit-content">
                    {% for module in modules %}<option value="{{module.id}}">{{module.name}}</option>{% endfor %}
                </select>
                <input type="submit" value="Submit" name="moduleassign-submit" class="btn btn-primary" style="width: fit-content; height: fit-content">
            </div>
        </div>

        <a href="{% url 'forum:createmodule' course_id=selected_course.uuid %}"><div class="btn btn-primary">+ New module</div></a>
    </div>
    {% endif %}

    <div class="accordion" id="module-accordion">
    {% for module in modules %}
        <div class="accordion-item">
            <h3 class="accordion-header" id="heading{{module.id}}">
                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{module.id}}" aria-expanded="true" aria-controls="collapse{{module.id}}">
                    <span>{{module.name}}</span>
                    {% if selected_course.owner == request.user and module.id != 0 %}
                    <a onclick="if (confirm('Are you sure you want to delete \'{{module.name}}\'?')){location.href='{% url 'forum:deletemodule' course_id=selected_course.uuid module_id=module.id %}'}" class="bi bi-trash ms-4 link-secondary"></a>
                    {% endif %}
                </button>
            </h3>
            <div id="collapse{{module.id}}" class="accordion-collapse collapse show" aria-labelledby="heading{{module.id}}">
                <div class="accordion-body">
                    {% if module.assignments|length == 0 %}
                    <p>Module is empty!</p>
                    {% endif %}
                    <div class="list-group">
                        {% for assn in module.assignments %}
                        <label class="list-group-item" style="display: flex;">
                            {% if selected_course.owner == request.user %}
                            <input name="assignment-checkbox-{{assn.id}}" class="form-check-input me-3" type="checkbox" value="checked">
                            {% endif %}
                            <a href='{% url 'forum:assignmentdetails' course_id=selected_course.uuid assignment_id=assn.id %}' style="flex: 1 2 auto">
                                <div class="cutebox" style="background-color: var(--main-background-overlay); display: flex; flex-direction: row; justify-content: space-between;">
                                    <span>{{assn.title}}</span>
                                    <span>Due: {{assn.end_datetime}}</span>
                                </div>
                            </a>
                        </label>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
</form>
{% endblock %}

forum/templates/newassignment.html
{% extends 'base.html' %}

{% block title %}
New Assignment
{% endblock %}

{% block content %}
<h2>Create a new assignment</h2>
<form action="{% url 'forum:newassignment' course_id=selected_course.uuid %}" method="post" style="max-width: 800px;">
    {% csrf_token %}
    <div class="form-group">
        <label for="title">Title:</label>
        {{form.title}}
        <script>$("input[name='title']").addClass("form-control")</script>
    </div>
    <div class="form-group">
        <label for="start_datetime">Start:</label>
        {{form.start_datetime}}
        <script>$("input[name='start_datetime']").addClass("form-control")</script>
    </div>
    <div class="form-group">
        <label for="end_datetime">Deadline:</label>
        {{form.end_datetime}}
        <script>$("input[name='end_datetime']").addClass("form-control")</script>
    </div>
    <div class="form-group">
        <label for="description">Description:</label>
        {{form.description}}
    </div>
    <div class="form-group">
        <label for="total_points">Total points:</label>
        {{form.total_points}}
        <script>$("input[name='total_points']").addClass("form-control")</script>
    </div>
    <div class="form-group">
        <label for="module">Module:</label>
        {{form.module}}
        <script>$("select[name='module']").addClass("form-select")</script>
    </div>
    <input class="btn btn-primary mt-3" type="submit" value="Submit">

    <script>
        document.getElementsByName("start_datetime")[0].type = "datetime-local";
        document.getElementsByName("end_datetime")[0].type = "datetime-local";
        document.getElementsByName("module")[0].innerHTML += `<option value="No module"></option>`;
    </script>
    {% for assnmodule in modules %}
    <script>
        document.getElementsByName("module")[0].innerHTML += `<option value="{{assnmodule}}">{{assnmodule}}</option>`;
    </script>
    {% endfor %}
</form>
{% endblock %}