aristotle/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
import aristotle.views as core_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', core_views.home, name='home'),
    path('authentication/', include('authentication.urls'), name='authentication'),
    path('forum/', include('forum.urls'), name='forum'),
]

authentication/urls.py
from django.urls import path

from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'authentication'
urlpatterns = [
    path('login', LoginView.as_view(template_name="login.html"), name='login'),
    path('signup', views.signup, name='signup'),
    path('logout', LogoutView.as_view(next_page='home'), name='logout'),
]

forum/urls.py
from forum.views_folder import views_assignments, views_courses, views_modules, views_students, views_submissions
from django.urls import path

from .views_folder import views

app_name = 'forum'
urlpatterns = [
    path('', views.index, name='index'),
    path('course_id=<course_id>/', views.index, name='index'),
    
    path('course_id=<course_id>/students/', views_students.students, name='students'),
    path('course_id=<course_id>/students/grades/student_id=<student_id>/', views_students.studentgrades, name='studentgrades'),

    path('course_id=<course_id>/courses/', views_courses.courses, name='courses'),
    path('courses/', views_courses.courses, name='courses'),
    path('course_id=<course_id>/setcourse/', views_courses.setcourse, name='setcourse'),
    path('course_id=<course_id>/removefrompinned/', views_courses.removefrompinned, name='removefrompinned'),
    path('createcourse/', views_courses.createcourse, name='createcourse'),

    path('course_id=<course_id>/assignments/', views_assignments.assignments, name='assignments'),
    path('course_id=<course_id>/assignments/newassignment/', views_assignments.newassignment, name='newassignment'),
    path('course_id=<course_id>/assignments/assignment_id=<assignment_id>/delete/', views_assignments.delete_assignment, name='delete_assignment'),
    path('course_id=<course_id>/assignments/assignment_id=<assignment_id>/', views_assignments.assignmentdetails, name='assignmentdetails'),
    
    path('course_id=<course_id>/assignments/assignment_id=<assignment_id>/submit/', views_submissions.newsubmission, name='newsubmission'),
    path('course_id=<course_id>/assignments/submissions/assignment_id=<assignment_id>/student_id=<student_id>/', views_submissions.viewsubmission, name='viewsubmission'),
    
    path('course_id=<course_id>/modules/', views_modules.modules, name='modules'),
    path('course_id=<course_id>/createmodule/', views_modules.createmodule, name='createmodule'),
    path('course_id=<course_id>/deletemodule/module_id=<module_id>', views_modules.deletemodule, name='deletemodule'),
]

templates/base.html
{% load static %}

<html>
    <head>
        <title>aristotle° - {% block title %}{% endblock %}</title>
        <!-- JQuery -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

        <!-- Bootstrap CDNs -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

        <!-- Quill CDN -->
        {% include 'django_quill/media.html' %}

        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        <link rel="icon" href="{% static 'img/favicon.ico' %}">
    </head>
    <body>
        <div id=pagehead>
            <div style="display:flex; flex-direction: row; align-items: center;">
                {% if selected_course.uuid %}
                <a href="{% url 'forum:index' course_id=selected_course.uuid %}" style="color: white; font-weight: 500;">aristotle°</a>
                {% else %}
                <a href="{% url 'forum:index' %}" style="color: white; font-weight: 500;">aristotle°</a>
                {% endif %}
            </div>
            <div style="font-weight: normal">
                {{selected_course.name}}
            </div>
        </div>
        <div id="fullcontainer">
            {% if username %}
            <div id="navbar">
                <ul>
                    {% if selected_course.uuid %}
                    <a href="{% url 'forum:index' course_id=selected_course.uuid %}"><li>Home</li></a>
                    {% else %}
                    <a href="{% url 'forum:index' %}"><li>Home</li></a>
                    {% endif %}

                    {% if selected_course.uuid %}
                    <a href="{% url 'forum:courses' course_id=selected_course.uuid %}"><li>Courses</li></a>
                    {% else %}
                    <a href="{% url 'forum:courses' %}"><li>Courses</li></a>
                    {% endif %}

                    {% if selected_course %}
                    {% if selected_course.owner == request.user %}<a href="{% url 'forum:students' course_id=selected_course.uuid %}"><li>Students</li></a>{% endif %}
                    <a href="{% url 'forum:modules' course_id=selected_course.uuid %}"><li>Modules</li></a>
                    <a href="{% url 'forum:assignments' course_id=selected_course.uuid %}"><li>Assignments</li></a>
                    {% endif %}
                </ul>
                <ul>
                    <li>Logged in as <b>{{username}}</b></li>
                    <a href="{% url 'authentication:logout' %}"><li>Log Out</li></a>
                </ul>
            </div>
            {% endif %}
            <div id="content">
                {% block content %}
                {% endblock %}
            </div>
        </div>
        <div id="pagefoot">
            <span>Unsafe release.<br><a href="http://brandonssandbox.com" style="color:var(--always-white); text-decoration: underline;">Brandon Lee</a>, &#169; 2021.</span>
            
            {% if selected_course.uuid %}
            <a href="{% url 'forum:index' course_id=selected_course.uuid %}" style="font-size: xx-large; font-weight: 500; color: white">aristotle°</a>
            {% else %}
            <a href="{% url 'forum:index' %}" style="font-size: xx-large; font-weight: 500; color: white">aristotle°</a>
            {% endif %}

            <div>
                <div style="text-align: right;">
                    <a href="https://github.com/dabslee/aristotle/issues" style="color:var(--always-white); text-decoration: underline;">Report an issue</a>
                    <br>
                    <div style="display: flex; flex-direction: row;">
                        Share: <br>
                        <div id='shareLinks' style='display:flex;flex-direction:row;font-size: 16px;'> <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> <a id="Facebook-share-icon" class="fa fa-facebook" target="_blank"></a> <script> var curr = window.location.href; document.getElementById("Facebook-share-icon").href = `https://www.facebook.com/sharer/sharer.php?u=${curr}`; </script> <a id="Twitter-share-icon" class="fa fa-twitter" target="_blank"></a> <script> var curr = window.location.href; document.getElementById("Twitter-share-icon").href = `http://www.twitter.com/share?url=${curr}`; </script> <a id="LinkedIn-share-icon" class="fa fa-linkedin" target="_blank"></a> <script> var curr = window.location.href; document.getElementById("LinkedIn-share-icon").href = `https://www.linkedin.com/sharing/share-offsite/?url=${curr}`; </script> <a id="Pinterest-share-icon" class="fa fa-pinterest" target="_blank"></a> <script> var curr = window.location.href; document.getElementById("Pinterest-share-icon").href = `http://pinterest.com/pin/create/link/?url=${curr}`; </script> <a class="fa fa-share" href="javascript:void(0);" onclick="copyUrlToClipboard()"></a> <script> function copyUrlToClipboard() { var dummy = document.createElement("textarea"); document.body.appendChild(dummy); dummy.value = window.location.href; dummy.select(); document.execCommand("copy"); document.body.removeChild(dummy); alert("Share link copied to clipboard!"); } </script> <style> .fa { text-decoration: none; color: #ffffff; border-radius: 0%; padding: 0px; padding-top: 3px; padding-bottom: -3px; margin: 0 1px; width: 20px; height: 20px; text-align: center; } .fa:hover{opacity: 0.5;} </style> </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

templates/home.html
{% load static %}

<html>
    <head>
        <title>aristotle°</title>
        <!-- JQuery -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

        <!-- Bootstrap CDNs -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

        <!-- Quill CDN -->
        {% include 'django_quill/media.html' %}

        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        <link rel="icon" href="{% static 'img/favicon.ico' %}">
    </head>
    <body>
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320" style="position:absolute; left:0; top:0; height:80%; z-index: 0">
            <path fill="#2395d8" fill-opacity="1" d="M0,192L80,202.7C160,213,320,235,480,213.3C640,192,800,128,960,96C1120,64,1280,64,1360,64L1440,64L1440,0L1360,0C1280,0,1120,0,960,0C800,0,640,0,480,0C320,0,160,0,80,0L0,0Z"></path>
        </svg>
        <div id="splash-center">
            <h1 id="splash-header">aristotle°</h1>
            <div id="splash-box">
                <h2>Welcome!</h2>
                    Welcome to <a href="{% url 'home' %}">aristotle.com</a>, a free learning management system for tutors, parents, and students. <a href="{% url 'authentication:login' %}">Log in</a> or <a href="{% url 'authentication:signup' %}">register</a> in order to get started.
                </p>
                <div class="mt-4" style="display: flex; flex-direction: column; align-items: center; width: 100%">
                    <a href="{% url 'authentication:login' %}" class="btn btn-primary mb-2">Log In</a>
                    <a href="{% url 'authentication:signup' %}" class="btn btn-primary">Sign Up</a>
                </div>
            </div>
            <div id="splash-footer" class="mt-2">
                <a href="https://github.com/dabslee/aristotle/blob/master/README.md" target="_new" class="link-secondary">Help</a>
                <span class="ms-2 me-2">&#8226;</span>
                <a href="https://github.com/dabslee/aristotle" target="_new" class="link-secondary">View GitHub</a>
                <span class="ms-2 me-2">&#8226;</span>
                <a href="https://github.com/dabslee/aristotle/issues" target="_new" class="link-secondary">Send Feedback</a>
            </div>
        </div>
        <a href="http://brandonssandbox.com/" target="_new" class="link-secondary" style="position:absolute; bottom: 10px; right: 15px;">© Brandon Lee, 2021. All rights reserved.</a>
    </body>
    <style>
        html {
            width: 100%;
            height: 100%;
        }
        body {
            display: flex;
            align-items: center;
            justify-content: center;
            overflow:hidden;
            height: 100%;
            width: 100%;
            position: fixed;
            background-color: #eeeeee;
        }
        #splash-center {
            width: 35rem;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            z-index: 2;
        }
        #splash-box {
            background-color: var(--main-background);
            padding: 50px;
            border-radius: 20px;
            box-shadow: 0px 0px 50px rgba(0,0,0,0.3);
        }
        #splash-header {
            color: white;
            text-align: center;
        }
        .btn {
            width: 70%;
        }
        #splash-footer {
            display: flex;
            flex-direction: row;
            width: fit-content;
            align-items: center;
            justify-content: space-evenly;
        }
        .link-secondary {
            display: flex;
            align-items: center;
            justify-content: center;
        }
    </style>
</html>